#!/bin/bash
sqlplus -s system/baba1234 << EOF
SPOOL /home/oracle/Desktop/audit_report.txt
/*1.2*/
PROMPT 1.2 Ensure All Default Passwords Are Changed	
SELECT USERNAME
FROM DBA_USERS_WITH_DEFPWD
WHERE USERNAME NOT LIKE '%XS$NULL%';
/*1.3*/
PROMPT	1.3 Ensure All Sample Data And Users Have Been Removed	
SELECT USERNAME
FROM ALL_USERS
WHERE USERNAME IN ('BI','HR','IX','OE','PM','SCOTT','SH');
/*2.2.1*/
PROMPT	2.2.1 Ensure 'AUDIT_SYS_OPERATIONS' Is Set to 'TRUE'
SELECT UPPER(VALUE)
FROM V$PARAMETER
WHERE UPPER(NAME) = 'AUDIT_SYS_OPERATIONS';
/*2.2.3*/
PROMPT	2.2.3 Ensure 'GLOBAL_NAMES' Is Set to 'TRUE'
SELECT UPPER(VALUE)
FROM V$PARAMETER
WHERE UPPER(NAME)='GLOBAL_NAMES';
/*2.2.6*/
PROMPT 2.2.6 Ensure 'OS_ROLES' Is Set to 'FALSE'
SELECT UPPER(VALUE)
FROM V$PARAMETER
WHERE UPPER(NAME)='OS_ROLES';
/*3.1*/
PROMPT 3.1 Ensure 'FAILED_LOGIN_ATTEMPTS' Is Less than or Equal to '5'	
SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE RESOURCE_NAME='FAILED_LOGIN_ATTEMPTS'
AND
(
LIMIT = 'DEFAULT'
OR LIMIT = 'UNLIMITED'
OR LIMIT > 5
);
/*3.3*/
PROMPT 3.3 Ensure 'PASSWORD_LIFE_TIME' Is Less than or Equal to '90'	
SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE RESOURCE_NAME='PASSWORD_LIFE_TIME'
AND
(
LIMIT = 'DEFAULT'
OR LIMIT = 'UNLIMITED'
OR LIMIT > 90
);
/*3.9*/
PROMPT 3.9 Ensure 'SESSIONS_PER_USER' Is Less than or Equal to '10'
SELECT PROFILE, RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE RESOURCE_NAME='SESSIONS_PER_USER'
AND
(
LIMIT = 'DEFAULT'
OR LIMIT = 'UNLIMITED'
OR LIMIT > 10
);
/*4.1.1*/
PROMPT	4.1.1 Ensure 'EXECUTE' Is Revoked from 'PUBLIC' on 'DBMS_ADVISOR'	
SELECT PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE='PUBLIC'
AND PRIVILEGE='EXECUTE'
AND TABLE_NAME='DBMS_ADVISOR';
/*4.2.2*/
PROMPT 4.2.2 Ensure 'EXECUTE' Is Revoked from 'PUBLIC' on 'DBMS_BACKUP_RESTORE'
SELECT PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE='PUBLIC'
AND PRIVILEGE='EXECUTE'
AND TABLE_NAME='DBMS_BACKUP_RESTORE';
/*4.4.4*/
PROMPT	4.4.4 Ensure 'DBA' Is Revoked from Unauthorized 'GRANTEE'	
SELECT GRANTEE, GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTED_ROLE='DBA'
AND GRANTEE NOT IN ('SYS','SYSTEM');
/*5.1.1*/
PROMPT 5.1.1 Enable 'USER' Audit Option
SELECT AUDIT_OPTION, SUCCESS, FAILURE
FROM DBA_STMT_AUDIT_OPTS
WHERE AUDIT_OPTION='USER'
AND USER_NAME IS NULL
AND PROXY_NAME IS NULL
AND SUCCESS = 'BY ACCESS'
AND FAILURE = 'BY ACCESS';
/*5.1.2*/
PROMPT	5.1.2 Enable 'ALTER	USER' Audit Option
SELECT AUDIT_OPTION, SUCCESS, FAILURE
FROM DBA_STMT_AUDIT_OPTS
WHERE AUDIT_OPTION='ALTER USER'
AND USER_NAME IS NULL
AND PROXY_NAME IS NULL
AND SUCCESS = 'BY ACCESS'
AND FAILURE = 'BY ACCESS';
/*5.1.3*/
PROMPT	5.1.3 Enable 'DROP USER' Audit Option
SELECT AUDIT_OPTION, SUCCESS, FAILURE
FROM DBA_STMT_AUDIT_OPTS
WHERE AUDIT_OPTION='DROP USER'
AND USER_NAME IS NULL
AND PROXY_NAME IS NULL
AND SUCCESS = 'BY ACCESS'
AND FAILURE = 'BY ACCESS';
EXIT
EOF